/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSplatRouteImport } from './routes/posts.$'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as PresentationsSplatRouteImport } from './routes/presentations/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSplatRoute = PostsSplatRouteImport.update({
  id: '/posts/$',
  path: '/posts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/presentations/',
  path: '/presentations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsSplatRoute = PresentationsSplatRouteImport.update({
  id: '/presentations/$',
  path: '/presentations/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/presentations/$': typeof PresentationsSplatRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/presentations/$': typeof PresentationsSplatRoute
  '/presentations': typeof PresentationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/presentations/$': typeof PresentationsSplatRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/$' | '/presentations/$' | '/presentations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$' | '/presentations/$' | '/presentations'
  id: '__root__' | '/' | '/posts/$' | '/presentations/$' | '/presentations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsSplatRoute: typeof PostsSplatRoute
  PresentationsSplatRoute: typeof PresentationsSplatRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$': {
      id: '/posts/$'
      path: '/posts/$'
      fullPath: '/posts/$'
      preLoaderRoute: typeof PostsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/presentations'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/$': {
      id: '/presentations/$'
      path: '/presentations/$'
      fullPath: '/presentations/$'
      preLoaderRoute: typeof PresentationsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsSplatRoute: PostsSplatRoute,
  PresentationsSplatRoute: PresentationsSplatRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
